%% This script pulls simulated uEPSPs for all ORN-> PN connections
%
% These simulations are produced by using the script
% ../../nC_projects_lite/hocEd3.py to modify default .hoc files produced by neuroConstruct
% based on out PN dendrite w/ ORN input neuroML files
% (../../nC_projects_lite/pnDendritesWithORNInputsNeuroML)
%
% nC_projects_lite/ available at https://neurodata.io/data/tobin17
% download into the this repos root directory
%
%% Note: This code requires GNU Grep to run without modification

%% Load annotations and connectors

% Load annotations json. Generated by gen_annotation_map.py
annotations=loadjson('../../tracing/sid_by_annotation.json');

% Return all skeleton IDs for R and L ORNs
ORNs_Left=annotations.Left_0x20_ORN;
ORNs_Right=annotations.Right_0x20_ORN;
ORNs=[ORNs_Left, ORNs_Right];
            
%return all skeleton IDs of DM6 PNs
PNs=sort(annotations.DM6_0x20_PN);

%Load the connector structure
load('../../tracing/conns.mat')

%Base dir for simulation results
baseDir='../../nC_projects_lite/';

%% Collect simulation results for PN1LS

pn1LS_Vm=importdata(strcat(baseDir, 'PN1LS_allORNs/simulations/unitaries/neuron_PN1_LS_sk_419138_0.dat'));
pn1LS_simTime=importdata(strcat(baseDir, 'PN1LS_allORNs/simulations/unitaries/time.dat'));

%collect ORN skel IDs from PN1LS hoc file and save them in a txt file
idCommand=['grep -Po ''(?<=objref spikesource_)\d*'' ', ...
    baseDir,'PN1LS_allORNs/simulations/unitaries/PN1LS_allORNs.hoc > ',baseDir,'PN1LS_allORNs/simulations/unitaries/ornIDs.txt'];
    
system(idCommand);
ornSkelIDs=importdata([baseDir,'PN1LS_allORNs/simulations/unitaries/ornIDs.txt']);

fireTimeCmd=['grep -Po ''((?<=.start = )\d*)'' ', baseDir,...
    'PN1LS_allORNs/simulations/unitaries/PN1LS_allORNs.hoc > ',baseDir, 'PN1LS_allORNs/simulations/unitaries/ornSpikeTimes.txt'];
system(fireTimeCmd);
fireTimes=importdata([baseDir,'PN1LS_allORNs/simulations/unitaries/ornSpikeTimes.txt']);


%% Collect uEPSPs in an array

leftCounter=1;
rightCounter=1;


for o=1:length(ornSkelIDs)
    
    if ismember(ornSkelIDs(o),ORNs_Left) == 1
        
        leftUEPSPs{1}(leftCounter,:)= pn1LS_Vm(find(pn1LS_simTime==fireTimes(o))-160:find(pn1LS_simTime==fireTimes(o))+7840);
        leftContactNum{1}(leftCounter)=getSynapseNum(ornSkelIDs(o),PNs(1));
        
        %store the skeleton ID associated with each unitary in leftUEPSPs_idList
        leftUEPSPs_idList{1}(leftCounter)=ornSkelIDs(o);
        leftCounter=leftCounter+1;
      
    elseif ismember(ornSkelIDs(o),ORNs_Right) == 1
        
       rightUEPSPs{1}(rightCounter,:) = pn1LS_Vm(find(pn1LS_simTime==fireTimes(o))-160:find(pn1LS_simTime==fireTimes(o))+7840);
       rightContactNum{1}(rightCounter)=getSynapseNum(ornSkelIDs(o),PNs(1));
     

        rightUEPSPs_idList{1}(rightCounter)=ornSkelIDs(o);
        rightCounter=rightCounter+1;
        
       
    end
end

%% Collect simulation results for PN2LS

pn2LS_Vm=importdata(strcat(baseDir, 'PN2LS_allORNs/simulations/unitaries/neuron_PN2_LS_sk_427345_0.dat'));
pn2LS_simTime=importdata(strcat(baseDir, 'PN2LS_allORNs/simulations/unitaries/time.dat'));

%collect ORN skel IDs from PN1LS hoc file and save them in a txt file
idCommand=['grep -Po ''(?<=objref spikesource_)\d*'' ', ...
    baseDir,'PN2LS_allORNs/simulations/unitaries/PN2LS_allORNs.hoc > ',baseDir,'PN2LS_allORNs/simulations/unitaries/ornIDs.txt'];
    
system(idCommand);
ornSkelIDs=importdata([baseDir,'PN2LS_allORNs/simulations/unitaries/ornIDs.txt']);

fireTimeCmd=['grep -Po ''((?<=.start = )\d*)'' ', baseDir,...
    'PN2LS_allORNs/simulations/unitaries/PN2LS_allORNs.hoc > ',baseDir, 'PN2LS_allORNs/simulations/unitaries/ornSpikeTimes.txt'];
system(fireTimeCmd);
fireTimes=importdata([baseDir,'PN2LS_allORNs/simulations/unitaries/ornSpikeTimes.txt']);


%% Collect uEPSPs in an array


leftCounter=1;
rightCounter=1;


for o=1:length(ornSkelIDs)
    
    if ismember(ornSkelIDs(o),ORNs_Left) == 1
        
        leftUEPSPs{2}(leftCounter,:)= pn2LS_Vm(find(pn2LS_simTime==fireTimes(o))-160:find(pn2LS_simTime==fireTimes(o))+7840);
        leftContactNum{2}(leftCounter)=getSynapseNum(ornSkelIDs(o),PNs(2));
      
        
        %store the skeleton ID associated with each unitary in leftUEPSPs_idList
        leftUEPSPs_idList{2}(leftCounter)=ornSkelIDs(o);
        leftCounter=leftCounter+1;
        
        
    elseif ismember(ornSkelIDs(o),ORNs_Right) == 1
        
        rightUEPSPs{2}(rightCounter,:)= pn2LS_Vm(find(pn2LS_simTime==fireTimes(o))-160:find(pn2LS_simTime==fireTimes(o))+7840);
        rightContactNum{2}(rightCounter)=getSynapseNum(ornSkelIDs(o),PNs(2));
        
        
        rightUEPSPs_idList{2}(rightCounter)=ornSkelIDs(o);
        rightCounter=rightCounter+1;
        
      
        
    end
end


%% Collect simulation results for PN3LS

pn3LS_Vm=importdata(strcat(baseDir, 'PN3LS_allORNs/simulations/unitaries/neuron_PN3_LS_sk_668267_0.dat'));
pn3LS_simTime=importdata(strcat(baseDir, 'PN3LS_allORNs/simulations/unitaries/time.dat'));

%collect ORN skel IDs from PN3LS hoc file and save them in a txt file
idCommand=['grep -Po ''(?<=objref spikesource_)\d*'' ', ...
    baseDir,'PN3LS_allORNs/simulations/unitaries/PN3LS_allORNs.hoc > ',baseDir,'PN3LS_allORNs/simulations/unitaries/ornIDs.txt'];
    
system(idCommand);
ornSkelIDs=importdata([baseDir,'PN3LS_allORNs/simulations/unitaries/ornIDs.txt']);

fireTimeCmd=['grep -Po ''((?<=.start = )\d*)'' ', baseDir,...
    'PN3LS_allORNs/simulations/unitaries/PN3LS_allORNs.hoc > ',baseDir, 'PN3LS_allORNs/simulations/unitaries/ornSpikeTimes.txt'];
system(fireTimeCmd);
fireTimes=importdata([baseDir,'PN3LS_allORNs/simulations/unitaries/ornSpikeTimes.txt']);



%% Collect uEPSPs in an array

leftCounter=1;
rightCounter=1;


for o=1:length(ornSkelIDs)
    
    if ismember(ornSkelIDs(o),ORNs_Left) == 1
        
        leftUEPSPs{3}(leftCounter,:)= pn3LS_Vm(find(pn3LS_simTime==fireTimes(o))-160:find(pn3LS_simTime==fireTimes(o))+7840);
        leftContactNum{3}(leftCounter)=getSynapseNum(ornSkelIDs(o),PNs(5));
        
        %store the skeleton ID associated with each unitary in leftUEPSPs_idList
        leftUEPSPs_idList{3}(leftCounter)=ornSkelIDs(o);
        leftCounter=leftCounter+1;
        
        
        
    elseif ismember(ornSkelIDs(o),ORNs_Right) == 1
        
        rightUEPSPs{3}(rightCounter,:)= pn3LS_Vm(find(pn3LS_simTime==fireTimes(o))-160:find(pn3LS_simTime==fireTimes(o))+7840);
        rightContactNum{3}(rightCounter)=getSynapseNum(ornSkelIDs(o),PNs(5));
        
        rightUEPSPs_idList{3}(rightCounter)=ornSkelIDs(o);
        rightCounter=rightCounter+1;
       
        
    end
end


%% Collect simulation results for PN1RS

pn1RS_Vm=importdata(strcat(baseDir, 'PN1RS_allORNs/simulations/unitaries/neuron_PN1_RS_sk_638603_0.dat'));
pn1RS_simTime=importdata(strcat(baseDir, 'PN1RS_allORNs/simulations/unitaries/time.dat'));

%collect ORN skel IDs from PN3LS hoc file and save them in a txt file
idCommand=['grep -Po ''(?<=objref spikesource_)\d*'' ', ...
    baseDir,'PN1RS_allORNs/simulations/unitaries/PN1RS_allORNs.hoc > ',baseDir,'PN1RS_allORNs/simulations/unitaries/ornIDs.txt'];
    
system(idCommand);
ornSkelIDs=importdata([baseDir,'PN1RS_allORNs/simulations/unitaries/ornIDs.txt']);

fireTimeCmd=['grep -Po ''((?<=.start = )\d*)'' ', baseDir,...
    'PN1RS_allORNs/simulations/unitaries/PN1RS_allORNs.hoc > ',baseDir, 'PN1RS_allORNs/simulations/unitaries/ornSpikeTimes.txt'];
system(fireTimeCmd);
fireTimes=importdata([baseDir,'PN1RS_allORNs/simulations/unitaries/ornSpikeTimes.txt']);


%% Collect uEPSPs in an array

leftCounter=1;
rightCounter=1;


for o=1:length(ornSkelIDs)
    
    if ismember(ornSkelIDs(o),ORNs_Left) == 1
        
        leftUEPSPs{4}(leftCounter,:)= pn1RS_Vm(find(pn1RS_simTime==fireTimes(o))-160:find(pn1RS_simTime==fireTimes(o))+7840);
        leftContactNum{4}(leftCounter)=getSynapseNum(ornSkelIDs(o),PNs(4));
      
        %store the skeleton ID associated with each unitary in leftUEPSPs_idList
        leftUEPSPs_idList{4}(leftCounter)=ornSkelIDs(o);
        leftCounter=leftCounter+1;
        
        
    elseif ismember(ornSkelIDs(o),ORNs_Right) == 1
        
        rightUEPSPs{4}(rightCounter,:)= pn1RS_Vm(find(pn1RS_simTime==fireTimes(o))-160:find(pn1RS_simTime==fireTimes(o))+7840);
        rightContactNum{4}(rightCounter)=getSynapseNum(ornSkelIDs(o),PNs(4));
        
        rightUEPSPs_idList{4}(rightCounter)=ornSkelIDs(o);
        rightCounter=rightCounter+1;
       
        
    end
end

%% Collect simulation results for P21RS

pn2RS_Vm=importdata(strcat(baseDir, 'PN2RS_allORNs/simulations/unitaries/neuron_PN2_RS_sk_480245_0.dat'));
pn2RS_simTime=importdata(strcat(baseDir, 'PN2RS_allORNs/simulations/unitaries/time.dat'));

%collect ORN skel IDs from PN3LS hoc file and save them in a txt file
idCommand=['grep -Po ''(?<=objref spikesource_)\d*'' ', ...
    baseDir,'PN2RS_allORNs/simulations/unitaries/PN2RS_allORNs.hoc > ',baseDir,'PN2RS_allORNs/simulations/unitaries/ornIDs.txt'];
    
system(idCommand);
ornSkelIDs=importdata([baseDir,'PN2RS_allORNs/simulations/unitaries/ornIDs.txt']);

fireTimeCmd=['grep -Po ''((?<=.start = )\d*)'' ', baseDir,...
    'PN2RS_allORNs/simulations/unitaries/PN2RS_allORNs.hoc > ',baseDir, 'PN2RS_allORNs/simulations/unitaries/ornSpikeTimes.txt'];
system(fireTimeCmd);
fireTimes=importdata([baseDir,'PN2RS_allORNs/simulations/unitaries/ornSpikeTimes.txt']);


%% Collect uEPSPs in an array

leftCounter=1;
rightCounter=1;


for o=1:length(ornSkelIDs)
    
    if ismember(ornSkelIDs(o),ORNs_Left) == 1
        
        leftUEPSPs{5}(leftCounter,:)= pn2RS_Vm(find(pn2RS_simTime==fireTimes(o))-160:find(pn2RS_simTime==fireTimes(o))+7840);
        leftContactNum{5}(leftCounter)=getSynapseNum(ornSkelIDs(o),PNs(3));
      
        %store the skeleton ID associated with each unitary in leftUEPSPs_idList
        leftUEPSPs_idList{5}(leftCounter)=ornSkelIDs(o);
        leftCounter=leftCounter+1;
        
        
    elseif ismember(ornSkelIDs(o),ORNs_Right) == 1
        
        rightUEPSPs{5}(rightCounter,:)= pn2RS_Vm(find(pn2RS_simTime==fireTimes(o))-160:find(pn2RS_simTime==fireTimes(o))+7840);
        rightContactNum{5}(rightCounter)=getSynapseNum(ornSkelIDs(o),PNs(3));
        
        rightUEPSPs_idList{5}(rightCounter)=ornSkelIDs(o);
        rightCounter=rightCounter+1;
       
        
    end
end
