% This script should generate figure 3 panel F boxplots

% Load the inputR_responses.mat file. This is a cell array with an entry for
% each PN. Each PN entry contains an array of simulated voltage responses
% generated by injecting current into each section of each model. This file
% was generated by: ../../nC_projects_lite/measureInputR.m
%
% nC_projects_lite/ available at https://neurodata.io/data/tobin17
% download into the this repos root directory
%

load('../../nC_projects_lite_lite/inputR_responses.mat')

%Calculate the inputR for each compartment

for p=1:5
    
    for a=1:size(inputR_responses{p},1)
        
        inputR{p}(a)=(mean(inputR_responses{p}(a,12000:13500))+60)/0.01;
        
    end
  
end


% generate some group statistical descriptions
leftInputRs=[inputR{1},inputR{2},inputR{3}]/1000;
rightInputRs=[inputR{4},inputR{5}]/1000;

gpsU = [ones(size(leftInputRs)),2.*ones(size(rightInputRs))];
valsU = [leftInputRs,rightInputRs];
[YUmean,YUsem,YUstd,YUci] = grpstats(valsU,gpsU,{'mean','sem','std','meanci'});


%plotting
figure
set(gcf,'Color', 'w')
boxplot(valsU,gpsU, 'Colors','k', 'notch', 'on')

ax = gca;
ax.XTick = [1 2];
ax.XTickLabel = {'Left PNs';'RightPNs'};
ax.FontSize=16;
ylabel('Input R (GOhms)')
axis square
saveas(gcf,'leftRightInputR')
saveas(gcf,'leftRightInputR','epsc')


