% The code here should generate and save figure 2 panel E
% it relies on the package: 
% JSONLab: https://www.mathworks.com/matlabcentral/fileexchange/33381-jsonlab--a-toolbox-to-encode-decode-json-files

%% Load annotations and connectors
 clear

% Load annotations json. Generated by Wei's code gen_annotation_map.py
annotations=loadjson('../../tracing/sid_by_annotation.json');

% Return all skeleton IDs for R and L ORNs
ORNs_Left=annotations.Left_0x20_ORN;
ORNs_Right=annotations.Right_0x20_ORN;
ORNs=[ORNs_Left, ORNs_Right];

%return all skeleton IDs of DM6 PNs
PNs=sort(annotations.DM6_0x20_PN);

%Load the connector structure
load('../../tracing/conns.mat')

%gen conn fieldname list
connFields=fieldnames(conns);

%% Collect a list of presynaptic profile skeleton IDs for each PN

%Loop over all PNs
for p=1:5
    
counter=1;

%loop over all connectors
for i= 1 : length(connFields)
    
   %Make sure the connector doesnt have an empty presynaptic field
    if isempty(conns.(cell2mat(connFields(i))).pre) == 1 
        
   %or an empty postsynaptic field, if its empty it will be a cell
    elseif iscell(conns.(cell2mat(connFields(i))).post) == 1
        
    else
        
        %Check to see if the current PN is postsynaptic at this connector
        if sum(ismember(PNs(p), conns.(cell2mat(connFields(i))).pre))==1
            
            %If it is mark it
            counter=counter+1;
            
           
           
                
          
        else
        end
    end
end

pnOuts(p)=counter;


end


%% Plotting

figure()
bar([[pnOuts(1),pnOuts(2),pnOuts(5)];[0,pnOuts(4),pnOuts(3)]],.7, 'stacked')
set(gcf, 'Color', 'w')
colormap('winter')
ax=gca;
xlim([0 3]);
ax.XTick=[1:2];
ax.XTickLabel={'Left PNs', 'Right PNs'};
ax.FontSize=14;
ylabel('PN Outputs', 'FontSize', 16);

axis square

saveas(gcf,'pnOutSynNums')
saveas(gcf,'pnOutSynNums','epsc')


